<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0dba509b-3b8b-40e5-a45c-9daefd46b030</testSuiteGuid>
   <testCaseLink>
      <guid>d8c729df-568c-4c98-9392-5fdb811083dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/users/TC_1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669fc6e2-a57c-482f-98b8-602c3a9daeca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b7cc8ae-03aa-4c2c-91a6-0a1a14ef7c06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9824b392-ada9-4c4b-9496-6c4719b1f5fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal (user watched video)/TC_earn_point</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8284d451-bd08-4a91-adac-1aa38565da7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ep1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2526dcf2-e765-4be1-af61-65724d7fc33e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
