<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ab2da63e-b6d1-4636-bbfa-6db5270ab9be</testSuiteGuid>
   <testCaseLink>
      <guid>42b11177-225e-4a96-be54-0ff2eb2adb03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/users/TC_3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a9368e-7d87-4be1-8909-a8408edb7ad3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b99dc3e4-8a24-47b3-835e-c1a38a39781e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34e37828-81ba-4a73-9127-6d172810febf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal (user watched video)/TC_earn_point</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>16bd99ca-b092-454e-9e37-05aeb14ba853</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ep3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be5fd523-89a7-46d6-b94e-5013e494e8ed</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
