<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click here to see the full list_movies-image_1</name>
   <tag></tag>
   <elementGuidId>6fe53b20-73ed-4966-9bf8-eab9a8b9a9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Copshop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>movies-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Copshop</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://platform3-portalv3-production.s3.us-west-2.amazonaws.com/uniallaccess/moviecovers/191329211809_dvd_3d_clr-1.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done&quot;]/app-root[1]/app-upload-receipt[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid upload-receipt padding-top-100 balloons-background&quot;]/div[@class=&quot;movies-heading hide-on-init fadeIn animated&quot;]/app-movies-card[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container movies-card ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-sm-4 col-md-4 col-lg-2 ng-star-inserted&quot;]/div[@class=&quot;movies-image-container hide-on-init fadeIn animated&quot;]/a[1]/img[@class=&quot;movies-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Copshop']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
